import React from 'react';
import Dashboards from './Dashboard'
const Dashboard = () => {
  return (
    <div>
      <Dashboards></Dashboards>
    </div>
  );
}

export default Dashboard;

export async function generateMetadata({ params }) {
  return {
    title: 'Dashboard',
    deScription: 'Generated by kuldeep Singh'
  }
}