import React from 'react';
import Dashboards from './Dashboard'
const dataSet = async () => {
  const url = process.env.URI;
  try {
      const response = await fetch(`${url}/api/count`, {
          cache: "no-store",
      });
      // setData(response.data);
      const data = await response.json();
      return data;
  } catch (error) {
      console.log(error);
  }

}
const Dashboard = async() => {
  const data = await dataSet();
  return (
    <div>
      <Dashboards data={data}></Dashboards>
    </div>
  );
}

export default Dashboard;

export async function generateMetadata({ params }) {
  return {
    title: 'Dashboard',
    deScription: 'Generated by kuldeep Singh'
  }
}