import { Inter } from 'next/font/google';
import './globals.css';
import Head from 'next/head';
import Script from 'next/Script';
import Nav from './nav'
import "../assets/vendor/fonts/fontawesome.css"
import "../assets/vendor/fonts/tabler-icons.css"
import "../assets/vendor/fonts/flag-icons.css";
import "../assets/vendor/css/rtl/core.css"
import "../assets/vendor/css/rtl/theme-default.css"
import "../assets/css/demo.css";
import "../assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css";
import "../assets/vendor/libs/node-waves/node-waves.css";
import "../assets/vendor/libs/typeahead-js/typeahead.css";
import "../assets/vendor/libs/apex-charts/apex-charts.css";
import "../assets/vendor/libs/swiper/swiper.css";
import "../assets/vendor/libs/datatables-bs5/datatables.bootstrap5.css";
import "../assets/vendor/libs/datatables-responsive-bs5/responsive.bootstrap5.css";
import "../assets/vendor/libs/datatables-checkboxes-jquery/datatables.checkboxes.css";
import "../assets/vendor/css/pages/cards-advance.css";
import "../assets/vendor/libs/bs-stepper/bs-stepper.css"
import "../assets/vendor/libs/bootstrap-select/bootstrap-select.css"
import "../assets/vendor/libs/select2/select2.css"
import "../assets/vendor/libs/formvalidation/dist/css/formValidation.min.css"
import "../assets/vendor/css/pages/page-auth.css"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  deScription: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en"
      className="light-style layout-navbar-fixed layout-menu-fixed"
      dir="ltr"
      data-theme="theme-default"
      data-assets-path="../assets/"
      data-template="vertical-menu-template">




      <link rel="icon" type="image/x-icon" href="../assets/img/favicon/favicon.ico" />
      {/* <!-- Fonts --> */}
      <Head >
        <meta charset="utf-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0"
        ></meta>
      </Head>
      <Script
        src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
        crossorigin="anonymous"></Script>
      <Script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.perfect-scrollbar/1.5.5/perfect-scrollbar.min.js" integrity="sha512-X41/A5OSxoi5uqtS6Krhqz8QyyD8E/ZbN7B4IaBSgqPLRbWVuXJXr9UwOujstj71SoVxh5vxgy7kmtd17xrJRw==" crossorigin="anonymous" referrerpolicy="no-referrer"></Script>
      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></Script>
      <Script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js" integrity="sha512-2rNj2KJ+D8s1ceNasTIex6z4HWyOnEYLVC3FigGOmyQCZc2eBXKgOxQmo3oKLHyfcj53uz4QMsRCWNbLd32Q1g==" crossorigin="anonymous" referrerpolicy="no-referrer"></Script>
      <Script src="
https://cdn.jsdelivr.net/npm/hammerjs@2.0.8/hammer.min.js
"></Script>
      <Script src="
https://cdn.jsdelivr.net/npm/node-waves@0.7.6/dist/waves.min.js
"></Script>
      <Script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></Script>
      <Script src="https://cdnjs.cloudflare.com/ajax/libs/mmenu-js/9.3.0/mmenu.js" integrity="sha512-D1qgHT+xXRgN9gLLLYHbQ/c8wkrADqfXg1kr1dRbP9nOtNzIKKNDU+hmFqR1fSbsU1YFBkw6TbvfZo+SyI0K6w==" crossorigin="anonymous" referrerpolicy="no-referrer"></Script>
      <Script src='https://cdn.jsdelivr.net/npm/i18n-js@4.3.2/dist/browser/index.min.js'></Script>


      <Script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/10.3.1/swiper-bundle.js" integrity="sha512-4mlFrp9qno3Tz7HfKNi6hTnBS9Bb+Uzw6frb2U/4Jc0wHdL36LprwQqgDemKNvLVWSfoeQfrgLDDQA0N4oHxgA==" crossorigin="anonymous" referrerpolicy="no-referrer"></Script>

      {/* helper */}
      <Script src='https://cdn.jsdelivr.net/npm/helper-js@3.1.5/dist/index.iife.min.js'></Script>
      <body suppressHydrationWarning={true} >
        {/* <Nav/> */}
        {children}</body>
    </html>
  )
}
