import { Inter } from 'next/font/google';
import './globals.css';
import Head from 'next/head';
import Script from 'next/script'
import { ToastContainer } from 'react-toastify';
import { AuthProvider } from './Provider'
import 'react-toastify/dist/ReactToastify.css';
import ContextProvider from './context/ContextProvider';
import NextTopLoader from 'nextjs-toploader';
// import Nav from './nav'
import "../assets/vendor/fonts/fontawesome.css"
import "../assets/vendor/fonts/tabler-icons.css"
import "../assets/vendor/fonts/flag-icons.css";
import "../assets/vendor/css/rtl/core.css"
import "../assets/vendor/css/rtl/theme-default.css"
import "../assets/css/demo.css";
import "../assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css";
import "../assets/vendor/libs/node-waves/node-waves.css";
import "../assets/vendor/libs/typeahead-js/typeahead.css";
import "../assets/vendor/libs/apex-charts/apex-charts.css";
import "../assets/vendor/libs/swiper/swiper.css";
import "../assets/vendor/libs/datatables-bs5/datatables.bootstrap5.css";
import "../assets/vendor/libs/datatables-responsive-bs5/responsive.bootstrap5.css";
import "../assets/vendor/libs/datatables-checkboxes-jquery/datatables.checkboxes.css";
import "../assets/vendor/css/pages/cards-advance.css";
import "../assets/vendor/libs/bs-stepper/bs-stepper.css"
import "../assets/vendor/libs/bootstrap-select/bootstrap-select.css"
import "../assets/vendor/libs/select2/select2.css"
import "../assets/vendor/libs/formvalidation/dist/css/formValidation.min.css"

import "../assets/vendor/css/pages/page-auth.css"
import '../assets/vendor/css/pages/cards-advance.css'

// landing page
// import "../assets/css/bootstrap.min.css" 
import "../assets/css/LineIcons.2.0.css"
import "../assets/css/animate.css"
import "../assets/css/tiny-slider.css"
import "../assets/css/glightbox.min.css"
// import "../main/main.css" 
import { SpeedInsights } from '@vercel/speed-insights/next';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  deScription: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en"
      className="light-style layout-navbar-fixed layout-menu-fixed"
      dir="ltr"
      data-theme="theme-default"
      data-assets-path="../assets"
      data-template="vertical-menu-template">
      <link rel="icon" type="image/x-icon" href="/img/favicon/favicon.ico" />
      {/* <!-- Fonts --> */}
      <Head >
        <meta charset="utf-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0"
        ></meta>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous"></link>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous" />

        {/* <!-- Optional theme --> */}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous" />

      </Head>
      <body suppressHydrationWarning={true}>
        {/* <Nav/> */}
        <AuthProvider>
          <ContextProvider>
            <ToastContainer />
            <NextTopLoader  color="#7367F0"  crawlSpeed={200}/>
            {children}
            <SpeedInsights />
          </ContextProvider>
        </AuthProvider>
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></Script>

        {/* <Script src="./js/bootstrap.min.js"></Script> */}
        <Script src="/js/wow.min.js"></Script>
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></Script>
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/tiny-slider/2.9.2/min/tiny-slider.js"></Script>
        {/* <Script src="https://cdn.tailwindcss.com"></Script> */}
        <Script src="/js/glightbox.min.js"></Script>
        <Script src="/js/count-up.min.js"></Script>
        <Script src="/js/imagesloaded.min.js"></Script>
        <Script src="/js/isotope.min.js"></Script>
        <Script src="/js/main.js"></Script>
        <Script src="/js/embeded.js"></Script>
        {/* <Script src="https://cdn.tailwindcss.com"></Script> */}
      </body>

    </html>
  )
}
